name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_and_deploy:

    runs-on: [self-hosted]
    strategy:
      max-parallel: 4
      

    steps:
    - name: Install Dependencies
      run: |
        cd /home/apelsin4ik/actions-runner/sites/
        rm -rf DigitalAcademy
        git clone https://github.com/MrApelsin4ik/DigitalAcademy.git
        cd /home/apelsin4ik/actions-runner/sites/DigitalAcademy/DigitalAcademy

        python3 -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python3 manage.py test

    - name: deploying
      run: |
        cd /home/apelsin4ik/actions-runner/sites/DigitalAcademy/DigitalAcademy

        export DJANGO_DEBUG='false'
        export DJANGO_SECRET_KEY='django-insecure-_tiw8oli@f8)1@q*73b)h4!7r^@)k4y++3pu0lo&hgb2#1_8k)'
        
        # Migrate database
        python3 manage.py makemigrations
        python3 manage.py migrate
        

      
