name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: [self-hosted]
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.10]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        cd /home/apelsin4ik/actions-runner/sites/DigitalAcademy/DigitalAcademy

        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python3 manage.py test
  
  deploy:
    runs-on: [self-hosted]
    steps:
    - name: deploying
      run: |
        cd /home/apelsin4ik/actions-runner/sites/DigitalAcademy/DigitalAcademy

        export DJANGO_SECRET_KEY='django-insecure-_tiw8oli@f8)1@q*73b)h4!7r^@)k4y++3pu0lo&hgb2#1_8k)'
        export DJANGO_DEBUG='false'
        # Migrate database
        python3 manage.py makemigrations
        python3 manage.py migrate
        
        # Run server
        sudo python3 manage.py runserver 0.0.0.0:80

      
